language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"    
  - "3.7"
services:
  - mongodb
before_script:
  - easy_install distribute
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"admin",pwd:"test",roles:["readWrite"]});'
# command to install dependencies
install:
  - make dependencias
# command to run tests
script:
  - make tests