version: 1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      # Obtenemos codigo del repo
      - checkout

      - run:
          name: instalar mongo
          command: |
            sudo apt-get install mongodb 
      
      - run:
          name: iniciar mongo
          command: |
            sudo service mongodb start
      - run:
          name: Crear usuario mongo
          command: |
            mongo mydb_test --eval 'db.addUser({user:"admin",pwd:"test",roles:["readWrite"]});'
      # Instalar dependencias e iniciar
      - run:
          name: Instalar dependencias e iniciar
          command: |
            make initCircle
      # command to run tests
      - run:
          name: Run tests
          command: |
             make tests