version: 1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4  # primary container for the build job
    
    steps:
      # Obtenemos codigo del repo
      - checkout
      - run: sudo apt-get update 
      - run:
          name: Intalar rabbitMq
          command: |
            sudo apt-get install rabbitmq-server
      # Instalar dependencias e iniciar
      - run:
          name: Instalar dependencias e iniciar
          command: |
            make initCircle
      # command to run tests
      - run:
          name: Run tests
          command: |
             make tests