version: 1
jobs:
  build:
    docker:
      - image: messa/circleci-python-with-mongodb:3.6
    steps:
      # Obtenemos codigo del repo
      - checkout
      - run:
          name: Crear usuario mongo
          command: |
            mongo mydb_test --eval 'db.createUser({user:"admin",pwd:"test",roles:["readWrite"]});'
      # Instalar dependencias e iniciar
      - run:
          name: Instalar dependencias e iniciar
          command: |
            make initCircle
      # command to run tests
      - run:
          name: Run tests
          command: |
             make tests